### PR TITLE
Function organizations and basic listing and deleting of existing mappings

### LINKED ISSUE #14: Automap users if coming from KeyCloak
If coming from KeyCloak, having authenticated with OIDC connected to OSC LDAP, we should auto-map the users "KeyCloak account" with their OSC account, and redirect them to their original destination.

Therefore, this is the user flow for a first time OSC user logging in via KeyCloak:

screen shot 2017-03-22 at 4 31 22 pm
screen shot 2017-03-22 at 4 31 25 pm
screen shot 2017-03-22 at 4 31 28 pm

### PR DESCRIPTION
**Pull request by basilgohar**
Fixes #14

This is a really rough workflow (still has debug statements in it) but I wanted to give you a chance to review it since I will continue in this style if you don't see any issues.  This does not close out the branch yet, since automapping itself is not completed, these were just prerequisites for that.

### CODE REVIEW

**Comment by nickjer** [comment]
Hah, was playing with it on the dev server. You probably haven't gotten to this yet, but I noticed I can't click "Manage" without typing in my OSC username/password. Most likely the Manage view will have to be default for already mapped users.

**Comment by nickjer** [comment]
Also when I go to the management page, I see my username and **plain-text password** as hidden input fields in the HTML form. This is scary and not quite sure why they are necessary for removing a mapping.

**Comment by basilgohar** [comment]
@nickjer You're right.  I'm not satisfied with that.  Part of that is because I copied the base layout/structure from form.php, but part of it is also because I'm not sure what is the state of the user's authentication at this point nor how to validate that they are authorized to make these changes.

**Comment by nickjer** [comment]
I suggest using the [ood_auth_map](https://github.com/OSC/ood_auth_map/) tool for checking if `REMOTE_USER` is already mapped. In particular you'd run a command along the lines of:

```sh
/opt/ood/ood_auth_map/bin/ood_auth_map.mapfile '<url-escaped-remote-user>'
```

this will return the local user name or nothing (if not mapped) to stdout.

**Comment by basilgohar** [comment]
@nickjer I'm not sure how much I like that idea – I can figure out if they're mapped by just scanning the user's existing mappings and seeing if the current one is already there.  I do this already to detect the user's current mapping and highlight it for them.

My concern was how sure can I be, if they're running the register app, that the user is authorized to make all the changes the Apache is capable of doing for that user?  I don't have a session cookie that I can store user information into (at least, not exposed via $_SESSION) that will persist across page requests to give me confidence that the user is already authenticated and authorized to make the change.  That's why I pass around the auth creds.  It might be dumb, of course, I'm just explaining why I did it that way at this time.

**Comment by ericfranz** [comment]
> My concern was how sure can I be, if they're running the register app, that the user is authorized to make all the changes the Apache is capable of doing for that user?
>  I'm not sure what is the state of the user's authentication at this point nor how to validate that they are authorized to make these changes.

The user has to authenticate before being able to access register.php. The OIDC claim headers can be trusted to tell us who the user is. There is no reason to have a password appearing in a view.

My only object to using ood_auth_map would be that we aren't using that to set the mappings. `/register` should use the same interface (or level of abstraction) for both setting and getting mappings. So if we are going to use the https://github.com/OSC/ood_auth_mapdn scripts directly, we should do that for both setting and getting mappings.

**Comment by basilgohar** [comment]
@ericfranz The OIDC claim headers tell us what the IDP knows, but not all IDPs include the OSC account name clearly in them.

**Comment by nickjer** [comment]
@ericfranz:
> My only object to using ood_auth_map would be that we aren't using that to set the mappings. `/register` should use the same interface (or level of abstraction) for both setting and getting mappings.

The whole objective of `ood_auth_map` is to get the mapping. It was decided in a previous OOD meeting with Doug that `ood_auth_mapdn` is not responsible for getting the mapping.

@basilgohar:
> I can figure out if they're mapped by just scanning the user's existing mappings and seeing if the current one is already there. I do this already to detect the user's current mapping and highlight it for them.

But you don't know who the local user is. So how are you scanning for their mappings? Having them login every time on `/register` using their OSC credentials defeats the purpose of single sign-on.

This is why the tool `ood_auth_map` exists. It maps the OIDC user to the local user, so they don't need to log in again with their OSC credentials.

**Comment by ericfranz** [comment]
@nickjer yeah it was discussed, but requirements have changed. My point still stands was that:

>/register should use the same interface (or level of abstraction) for both setting and getting mappings

There is unfortunately no script available to use mapdn.py to get the user for a specific dn. I think we should request this. (well the code is on GitHub so we could branch and make the modification our selves and then make the proposal).

`ood_auth_map` reads from the gridmap file, not from the sql database; its at a different abstraction level. This presents a race condition when deleting the mapping of the user you are logged in as. 

If we use `ood_auth_map` we may need to determine a workflow that can ensure we avoid the race condition. Our current design was after deleting the mapping you are logged in as, we would present you with a page asking you to log out or re-register this DN with another username. If you clicked "re-register" it would take you back to `/register` which would auto-map you if your DN is from OSC-ldap provider and would present the web form if your DN is from a CILogon provider. When the user clicks "re-register" the gridmap file (and thus `ood_auth_map`) needs to have already been updated so the mapping the user deleted no longer exists.

Note: Basil and I talked offline and the design/workflow has changed. I'll post that shortly.

**Comment by nickjer** [comment]
> `ood_auth_map` reads from the gridmap file, not from the sql database; its at a different abstraction level. This presents a race condition when deleting the mapping of the user you are logged in as.

Not true, the changes to the mapfile are made live.

**Comment by ericfranz** [comment]
@basilgohar I talked with Jeremy offline. We reached a consensus. If the user is going to delete the mapping they are logged in as, we should probably just have the button say "Delete and Log Out" instead of giving them the option. That way its safe to use ood_auth_map to determine the logged in user. The command to run should be in the environment variable `OOD_USER_MAP_CMD` (https://github.com/OSC/ood-portal-generator/blob/1472da89b427389f2233dd9a36c37872241e8eae/templates/ood-portal.conf.erb#L61) with a single argument, the DN.

I'll include this in my update to the design.

**Comment by nickjer** [comment]
The more I think about, I am not opposed to keeping them logged in. We keep them logged in when we **add** the mapping. So keeping them logged in when we **delete** the mapping should not cause any issues. This is because both **add** and **delete** force update the local grid-mapfile right after the changes are made.

Also note, we do not cache the user mapping anymore on the proxy. So as soon as that mapfile is updated, the users will experience the corresponding behavior when navigating the OOD portal.

There will always be a delay effect on other hosts though, but this is also true for **add**ing the mapping as well.

**Comment by ericfranz** [comment]
I added the loose design notes here: https://github.com/OSC/ood_auth_registration/issues/14#issuecomment-291620700

This takes into account both my conversation with Basil and Jeremy's suggestions.

**Review by ericfranz — CHANGES_REQUESTED** [review]
see comment

**Comment by basilgohar** [comment]
Hey Eric, I wanted to close this year-plus long pull request but I did not want to do it without your knowledge.  Let me know if i can do it or if you want to just delete it.  ;)

**Comment by ericfranz** [comment]
Go ahead and close it! Thanks

**Pull request closed without merging**
